### ISSUE TITLE
How to set user roles based on app_metadata?

### ISSUE THREAD

**Issue by IgsuMustonen** [auth0/auth0-drupal#123]
So this isn't a bug neither a feature request but more like a support request.

The documentation about Claim for role values is quite short and maybe enough for experienced users, I'm new to Auth0 and relatively experienced in Drupal and well, I don't really understand what is the claim for the role mapping and where do I find it.

### Description

Main goal: To set user's role in Drupal based on app_metadata values. For example: 

- Add user in Auth0 and set its app_metadata with ` "roles": [ "editor" ] `

- User signs in to the Drupal site and his role is automatically set to "Editor" ( The role itself has already been defined in Drupal as a user role) 

If I understood correctly, this is what the "Claim for role mapping" does in this module, however I have not been able to get this to work. This far I have the app_metadata set, I have "roles" (without "") in "Claim for role mapping", and below I have "admin|administrator" and "editor|editor". When is sign in to Drupal with a user with the "editor" value in roles, I see "No changes to roles detected" in Watchdog.

### Environment

* Module version: 8.x-2.1
* Drupal version: 8.6.3
* PHP version: 7.1.24

**Comment by IgsuMustonen** [comment]
Solved by using Authorization extension and aading the roles definition to idToken using somethin like this: 
`
function (user, context, callback) {
  const namespace = 'https://myapp.example.com/';
  context.idToken[namespace + 'roles'] = user.user_metadata.roles;
  callback(null, user, context);
}

`
With the claim being in this case "https://myapp.example.com/roles"

**Comment by joshcanhelp** [comment]
Thanks for checking back in here, @IgsuMustonen, and apologies for the delay in getting back to you. 

For anyone else looking to do this, official documentation on the custom claims mentioned above is here:

https://auth0.com/docs/scopes/current/custom-claims

**Comment by ozeberle** [comment]
Hi @Igsu-Bravo, I'm facing the same issue as you faced. I want to change roles for some users as administrators.
Can you give me a little bit of low level information about what you did to make this work?
My environment specs are the same as you had.
I completed **Claim for role mapping** in Auth0 advanced configuration at Drupal configuration with "roles" (without quotes) and "admin|administrator" in **Mapping of Claim Role Values to Drupal Roles**.
Also, I activated **Authorization** extension module inside of Auth0, created a role **admin** and assigned this role to a few users.
Then I went to **Rules** menu (out of Authorization extension module) and created the same rule as you created with a little difference about that **namespace**. What namespace should I use there? Because I tried many Urls with any good results. Drupal tell me: 'no changes to role detected'.

Also I tried adding "roles" to app_metadata but nothing changed.

I read what @joshcanhelp posted but honestly, I didn't understand.
I hope you can help me soon.

**Comment by nevkatz** [comment]
This is all very helpful. I had a question about namespacing. Is it okay to use the URL of one of my Drupal sites as the name space? In this case, http://sso-test-1.edc.org/{claim} - it bothers me that it doesn't go to a real page, but maybe that doesn't matter. Thanks for any insight!
