### ISSUE TITLE
Vendor directory included in drupal 8 distribution

### ISSUE THREAD

**Issue by seamuslee001** [auth0/auth0-drupal#143]
### Description

Just wondering why the vendor directory was included in the drupal 8 download for the latest release when it wasn't previously. I would have thought the normal expectation would be is that auth0 and other libraries would be found in the root vendor directory for drupal 8, given that the standard way of installing for Drupal 8 is via composer. I can understand having a vendor directory in the module directory for Drupal 7 given Drupal 7 isn't primarily based on composer.

### Prerequisites

* [x] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [x] Are you reporting this to the correct repository?
* [x] Are there any related or duplicate Issues or PRs for this issue?

### Environment

Please provide the following:

* Module version:2.2
* Drupal version:8.6.16
* PHP version: 7.1
* Browser version, if applicable
* Additional modules/plugins/add-ons that might be affecting your instance

**Comment by joshcanhelp** [comment]
@seamuslee001 - Thanks for the post here. To be honest, I went back and forth with that before releasing this last version. We've had a number of customers download directly from DO and submit tickets about missing classes (missing vendor dir). The solution is to run Composer but it doesn't look like that is universal knowledge. Since this wouldn't hurt anyone using Composer and would help developers not using it, I decided to include it. 

Is there a better way to handle this for sites not using Composer? I'm open to suggestions!
