### ISSUE TITLE
Mapping user profile fields shows PHP notice

### ISSUE THREAD

**Issue by amedve** [auth0/auth0-drupal#154]
### Description

PHP error (notice) when mapping Claims to Profile Fields:
```Notice: Array to string conversion in Drupal\auth0\Controller\AuthController->auth0UpdateFields() (line 798 of modules/contrib/auth0/src/Controller/AuthController.php).```

It happens because of this line in the `auth0UpdateFields()`:
`$this->auth0Logger->notice('mapping ' . $mapping);`

The `$mapping` is an array. 

### Environment

- **Version of this library used:** 8.x-2.3  from drupal.org
- **Drupal version:** 8.7.8
- **PHP version:** PHP 7.2.23

**Comment by reszli** [comment]
There is also another notice in the same controller:

_Notice: Undefined index: email_verified in Drupal\auth0\Controller\AuthController->signupUser() (line 662 of modules/contrib/auth0/src/Controller/AuthController.php)._

due to the following code:
`if ($userInfo['email_verified'] || $isDatabaseUser) {`
which should be smth like:
`if (isset($userInfo['email_verified']) || $isDatabaseUser) {`
