### ISSUE TITLE
Support for linking accounts

### ISSUE THREAD

**Issue by arithmetric** [auth0/auth0-drupal#25]
I am working on a use case where it is important to allow users to link more than one social login to their Drupal account. For example, allowing users to sign in to their Drupal account from either their LinkedIn or Salesforce account.

This should be doable with Auth0's [account linking](https://auth0.com/docs/link-accounts) functionality, but it requires implementing the interface in Drupal.

I've built a simple working prototype of this functionality in the branch: https://github.com/arithmetric/auth0-drupal/tree/feature/linking_accounts_prototype

I'm posting here for any feedback or suggestions on the approach. Ideally this will be built in a way that can be useful for others and can be contributed here.

**Next Steps**
- In the prototype, all of the code is added to the auth0-drupal module. I think it would be preferable to move as much of the new code as possible into a submodule, which would be optional to enable.
- In the prototype, a second block with the Auth0 Lock widget is exposed where authenticated users can "login" again with a secondary account to link it to the active one. In a build out this would be replaced by a page where users can select any auth connection that is not already linked with their account. To accomplish this, Drupal will also need to store a list of the active connections for the configured Auth0 application profile.
- In the prototype, the ID token is stored in the database during each user's log in so that it can be used to authorize account linking. (Even so, the ID token may expire while the Drupal session is still active, so it may be necessary to have users re-authenticate with Auth0.) It may be more fool proof and would provide more security to not store all ID tokens in the database, but rather require users to re-authenticate with their primary account whenever they link accounts.

**Comment by glena** [comment]
Sorry for the delay.

I did a quick check and this looks good, but I think this should not be part of the sdk.

The proper way to handle this, in my opinion, is the following:

1. The plugin should provide a hook so you can attach to it and get the user data from there (profile, id_token).
2. Then you should be able to store it in the session or database (I would try to avoid it) as you prefer
3. Implement the user linking on your own (it is pretty straight forward since it is already resolved on the linking docs)

The reason is that there might be different posible implementations/validations that each one might want to do. This will make it easier for them to customise and this way there is less things to mantain in the future (and less discussions to have with people that needs different ways to do that)

what do you think?

**Comment by arithmetric** [comment]
@glena Thanks for the review. Overall I agree with the approach you suggest.

Unfortunately the project sponsoring this work has reprioritized this feature, so I will not be able to follow up immediately on the next steps.

**Comment by glena** [comment]
ok, just ping me when you get back to this so we can work it out.

Thank you
