### ISSUE TITLE
RE: email Sync

### ISSUE THREAD

**Issue by turnbuga** [auth0/auth0-drupal#50]
Just wondering - Does user email update to match registered social account that created a login - by enabling the module email address is locked. How can a user update that email address?

This comes up as I am integrating with MailChimp and allowing users to manage subscriptions in the user profile. Once a user signs up using Gmail, Facebook, etc - how do they update their email address.
Thanks.

**Comment by glena** [comment]
You cant change the password for a social connection in Auth0. The reason is that this data belongs to facebook and is updated on each login. The proper way to do it is to create a user_metadata attribute (for example `notifications_email`) where you store the email to send the MailChimp campaigns if ther user does not want to use the primary one and use this new attribute to synchronise users with MailChimp.

**Comment by turnbuga** [comment]
Hello Germán, Sorry for the radio silence - that makes absolute sense. I believe I am more interested in the email data associated with a social account - If someone updates their email address on facebook, do the records on Drupal update when that user logs into Drupal using that social connection. Again thank you - have another question related to twitter but will ask that question in a separate post.

**Comment by glena** [comment]
Gotcha, currently it does not but it should not be hard. At this point https://github.com/auth0/auth0-drupal/blob/1.x.x/auth0.module#L213 you need to update the user with the email you got from the auth0 profile. This way you will keep it in sync with their social profile.

BTW, when I said password I was talking about the email. sorry for the confusion
