### ISSUE TITLE
Auth0 module storing credentials in plain text in the database

### ISSUE THREAD

**Issue by cdnsteve** [auth0/auth0-drupal#51]
I've found that in version 2.02, the auth0 credentials are stored in the database as clear text in the `config` table. Advise this be encrypted or offloaded to phpdotenv, where credentials are stored outside the database in a `.env` and kept out of version control for better security. 

https://github.com/vlucas/phpdotenv

**Comment by glena** [comment]
do you mean the client_id and secret?

**Comment by cdnsteve** [comment]
@glena yes.

**Comment by glena** [comment]
Having it in the database or in a file it pretty much the same because it will continue to be unencrypted. If you have it in the database someone can get its info with sql injection but it is similar to having it in the fail if the attacker can dump it. 

Since this package is focused to be used in a CMS the goal is to make it administrable from the settings section and that is wht it is in there.

Anyway, being it opensource you can easily change it for your site to pick it from your env vars.

When I have the chance I will make it configurable (let you pick if you want to use the database or an env var, the second case will disable the fields in the configuration page).

**Comment by darrenmothersele** [comment]
@cdnsteve you should store a dummy value in the config setting and then override in settings.php, where you can read it from an environment variable.

https://www.drupal.org/docs/8/api/configuration-api/configuration-override-system

**Comment by joshcanhelp** [comment]
Leaving this open to add to a README
