### ISSUE TITLE
Use of Twitter to authenticate

### ISSUE THREAD

**Issue by turnbuga** [auth0/auth0-drupal#52]
This is more of a survey to see if anyone has attempted to use Twitter as a social connection. The main gotcha in this is that twitter, by default, does not share the user email address when an auht0 account is created. There is a way request access of the email address with rules, but as the address is returned after account creation then users signing up in drupal receive a message confirm email, but email is never sent. The auth0 account is established but on applications where email is required it can never be utilised.  Any thoughts are appreciated - this is only impactful to those attempting to use twitter as a social connection,
Thank you.

**Comment by glena** [comment]
Are you using drupal 7 or 8?

**Comment by turnbuga** [comment]
7 at the moment

**Comment by glena** [comment]
I guess you are talking about this rule https://github.com/auth0/rules/blob/master/rules/get-twitter-email.md

try adding `user.email_verified = true;` after the callback at the bottom, it should look like this:


```php
    try {
      result = JSON.parse(body);
    } catch (e) {
      return callback(new Error('Invalid JSON returned by Twitter'));
    }
    if (!result.email) {
      // Might not want to fail in this case
      return callback(new Error('Twitter did not return an email address'));
    } else {
      user.email = result.email;

      user.email_verified = true; // <-------- This is the new line!

      return callback(null, user, context);
    }
  });
}
```

Since twitter does not provide an email, auth0 does not add this attribute to the profile. Later when the rule adds the email, that flag is still missing so the module assume the email is not verified.
