### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by justinlevi** [auth0/auth0-drupal#91]
I'm a bit confused about the user management with this module. If I have a bunch of existing Drupal users already, what am I supposed to do here? The documentation makes it seem like they should just work, but that doesn't seem right to me. 

I can create a user in Auth0 but then what happens if I update the password in Drupal? What about if I change the email in drupal? How are the user's email and password synced? Are they?

**Comment by joshcanhelp** [comment]
@justinlevi

First, I'll say that the documentation for this module definitely needs updating and we're working on that now, along with a few updates to how the login is handled. We're also working with the DO community to get the module up to Drupal coding standards and make sure what's available on DO is the same as what's here. 

Are for your specific question about users ... Auth0 can't verify an existing Drupal account so the best that can be done is matching an Auth0 user with a Drupal user, which is done by email. Once the two are linked, users will log in with Auth0 and be authenticated on your Drupal site with their existing email. 

As for adding them, users will either need to signup through Auth0 with the same email they used before or they can be [bulk imported via API](https://auth0.com/docs/users/migrations/bulk-import) (requires code to be written). 

I agree that the `readme.txt` here is a little misleading. Because passwords are hashed when stored, there's no way to make their existing password work, best we can do is match by email. 

As for profile updates like passwords, those are not synced to Auth0 currently.
