### ISSUE TITLE
Way to login as admin

### ISSUE THREAD

**Issue by timrabbetts** [auth0/auth0-drupal#97]
There is no way to login as admin tried email and password and doesnt work, I guess the normal login isnt working.  Be good to be able to login as admin.

**Comment by timrabbetts** [comment]
That didnt work, I am trying to login as admin to the drupal site through
the auth0 portal, first it says need email, I put in admin email and it
fails.

[image: Drupal Contactor]
*Tim Rabbetts*
Drupal Contractor
email: timrabbetts@gmail.com
phone: + 07730 327 508
[image: Twitter icon]  <https://twitter.com/timrabbetts>[image: LinkedIn
icon] <https://www.linkedin.com/in/timrabbetts/> www.timrabbetts.com

**Comment by joshcanhelp** [comment]
@timrabbetts - I'll run through the process again on my end tomorrow or Monday and see if I find any holes.

**Comment by timrabbetts** [comment]
Had no joy with this.  To be clear.  I dont want to login with a new user linked to drupal account.  I want to login as the root user which already exists prior to auth0.  When I try and put admin/mypassword and hit login, it fails says "invalid email" so I put in the admin email and it fails "something went wrong".  I just want to be able to do standard/normal drupal login with root user while auth0 login is enabled, can you help advise?  I have tried enable the checkbox for link user not difference.

**Comment by timrabbetts** [comment]
At the moment I have a split config and constantly importing configs when working on this which is a pain.

**Comment by timrabbetts** [comment]
Not sure I quite follow, the user doesnt exist on Auth0.  I have setup auth0 on drupal and now I face this form: 
![auth0](https://user-images.githubusercontent.com/12124608/40428274-cd8ae41a-5e97-11e8-826c-0b2cd9dbe587.png)
I want to use my drupal admin user, which doesnt exist anywhere on auth0, to login through the normal drupal login process, the process that this form has replace.  When I try with admin and my password, i get error saying I must use email address.  I then use my admin users email address and I get this: 

WE'RE SORRY, SOMETHING WENT WRONG WHEN ATTEMPTING TO LOG IN.

Better message would be good.  Is this possible?

**Comment by timrabbetts** [comment]
This I get what you were suggesting, create the row on the table, and a user in auth0 still same result.

**Comment by joshcanhelp** [comment]
@timrabbetts - That message is more of a general "something went wrong." User-specific errors are called out explicitly (incorrect password, user doesn't exist, etc). Sounds like you might have a problem in your configuration. Did you sign up first before logging in? Are there any errors in the JS console? Double-check your domain, client ID, and secret in Drupal as well as the callback and origin URLs in Auth0.

**Comment by timrabbetts** [comment]
got something working now, so I used auth0 to sign up then I edited the table and changed the drupal id to the admin uid rather than the new users uid.  Now I can login and get into the admin account.  Thats fine for now but just being able to use the admin ccreds would be better for future?

**Comment by joshcanhelp** [comment]
That's how it does work on my end but I'll make sure to test it again based on your feedback here. Obviously adding directly to the DB is not expected/desired behavior.

**Comment by timrabbetts** [comment]
Just so I understand this process.  I created a new user on the Auth0 UI.  Then I should be able to login through the Auth0 user/password form using those credentials?  As I just tried and it didnt work.  
WE'RE SORRY, SOMETHING WENT WRONG WHEN ATTEMPTING TO LOG IN.
Now before I can manually add entry to auth0 users table and it works but thats no use.  We are not using the social login stuff like google.  So I just need the form to login using auth0 users (which will be migrating into auth0).  I get same error, it looks like its cause the user doesnt exist on the drupal auth0 users table.  But shouldn't it talk to auth0 on login and create entry on the table, can you help test this as major blocker for the service.

**Comment by joshcanhelp** [comment]
> Then I should be able to login through the Auth0 user/password form using those credentials?

Correct. I just tested on a fresh install and everything worked as expected. I have **Link auth0 logins to drupal users by email address** turned on and **Requires verified email** turned off in the Advanced settings (the former is what makes this happen, the latter should not affect it). 

This is on a fresh install, though. If you already had it setup differently and already started signup up or logging in, you might have a mismatch that the module can't address.

> WE'RE SORRY, SOMETHING WENT WRONG WHEN ATTEMPTING TO LOG IN.

This is usually a configuration problem. If you have an incorrect login, it will tell you that. Make sure to review the settings in you Application on Auth0 to make sure the URLs and everything are correct. Also check the JS console to see if there's an error message there. 

> But shouldn't it talk to auth0 on login and create entry on the table

Yes, it definitely should. Again, that warning has more to do with configuration. The Auth0 login form only talks with Auth0, it doesn't do anything on your site until you've successfully authenticated and are redirected back. 

Two things to try:

- Change the "Widget CDN" URL to `https://cdn.auth0.com/js/lock/11.7/lock.min.js` to use the latest version.
- Try turning on **Redirect login for SSO** on the Advanced tab. That will use our universal login page instead of loading it on your site. It's generally better to use that but might be good to just try it as a test.

**Comment by rob3000** [comment]
Hey @timrabbetts to login to drupal using the original admin you can go to `/user/login/legacy` which exposes the old drupal login form so admins can still login.

**Comment by timrabbetts** [comment]
Works great thanks, prob worth getting this in the docs! thanks

**Comment by joshcanhelp** [comment]
Thanks @rob3000!

@timrabbetts - I'll make sure that gets added.
